###########################################################
# Course: CS 480-01, Summer 2026
# Instructor: Guy Leonard
# Assignment Information: Programming Assignment #3, Disk Arm Scheduling Algorithms

# Team Members:
# - Daynelle Lorin Sadangsal (cssc3154)
# - Sophia Phung (cssc3147)

# FileName: Makefile
###########################################################

CC = g++
CFLAGS = -Wall -Wextra -std=c++11

TARGET = simarm
SRC = main.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)

#######################[ EOF: Makefile ]###################